package productdata

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

// newRandomID generates an opaque, unguessable id. Used only for documents
// created inside this package itself (currently: User, on first sight of a
// verified identity) -- Equipment/ProjectEquipment ids are generated by the
// httpapi layer using the same convention already established for
// projects.NewID, so all user-facing ids in this codebase come from one
// place.
func newRandomID(prefix string) (string, error) {
	buf := make([]byte, 12)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("productdata: generate id: %w", err)
	}
	return prefix + "-" + hex.EncodeToString(buf), nil
}
